stgrest:
  image: pg_local
  ports:
    - "3000:3000"
  links:
    - postgres:postgres
  environment:
    PGRST_DB_URI: postgres://oppostarter:nHu6nv6rQSJEAKx@oppostarter.ct79ijtuhzf6.us-east-2.rds.amazonaws.com/oppostarter
    PGRST_DB_SCHEMA: 1
    PGRST_DB_ANON_ROLE: anonymous

postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: app_db
    POSTGRES_USER: app_user
    POSTGRES_PASSWORD: password
